"""
Transport-independent ECAM protocol layer.

Pure Python: frame builders, answer parsers, machine dialect profiles,
the write-gate session helper, native ``0xA2`` statistics, profile-name
blobs, writable settings and the recipe catalogue. No network or Home
Assistant imports live here — callers hand transports in.
"""

from cremalink.ecam.answers import (
    answer_flag,
    answer_id,
    decode_a2_page,
    is_sync_timeout,
    parse_a9_ack,
    parse_simple_ack,
    parse_write_ack,
)
from cremalink.ecam.builder import (
    ANSWER_PREFIX,
    ANSWER_SYNC_TIMEOUT,
    CMD_PREFIX,
    DEFAULT_RECIPE,
    BrewAction,
    PowerCommand,
    brew_param_included,
    build_bean_system,
    build_brew,
    build_factory_descriptor,
    build_monitor_request,
    build_power,
    build_priority_list,
    build_profile_names,
    build_profile_select,
    build_read,
    build_read_block,
    build_read_param,
    build_read_params,
    build_recipe_names,
    build_recipe_values,
    build_statistics_page,
    build_striker_handshake,
    build_write_param,
    encode_for_transport,
    trim_frame,
    verify_frame,
)
from cremalink.ecam.catalog import (
    BEAN_SYSTEM_IDS,
    CUSTOM_SLOT_IDS,
    TEXT_BLOB_FAMILIES,
    Beverage,
    RecipeCatalogue,
    blob_family,
    build_catalog,
    catalog_beverage_ids,
    decode_blob,
    fingerprint,
    parse_tlv,
    parse_triples,
)
from cremalink.ecam.machine_profiles import (
    NON_STRIKER,
    SESSION_DEVICE_CONNECTED_TS,
    SESSION_E8_APPID,
    STRIKER,
    TRAILER_APP_ID,
    TRAILER_NONE,
    MachineProfile,
    profile_from_map,
)
from cremalink.ecam.profiles import ProfileSlot, parse_profile_names
from cremalink.ecam.session import SessionGate
from cremalink.ecam.settings import (
    SETTING_OPTION_MAPS,
    WritableSetting,
    parse_settings,
)
from cremalink.ecam.statistics import (
    CLOUD_COUNTER_CANDIDATES,
    STAT_LABELS,
    StatisticEntry,
    StatisticsReport,
    counter_breakdown,
    interpret,
    parse_counter_value,
    parse_water_volume_liters,
    resolve_cloud_breakdowns,
    resolve_cloud_counters,
)

__all__ = [
    "ANSWER_PREFIX",
    "ANSWER_SYNC_TIMEOUT",
    "BEAN_SYSTEM_IDS",
    "CLOUD_COUNTER_CANDIDATES",
    "CMD_PREFIX",
    "CUSTOM_SLOT_IDS",
    "DEFAULT_RECIPE",
    "NON_STRIKER",
    "SESSION_DEVICE_CONNECTED_TS",
    "SESSION_E8_APPID",
    "SETTING_OPTION_MAPS",
    "STAT_LABELS",
    "STRIKER",
    "TEXT_BLOB_FAMILIES",
    "TRAILER_APP_ID",
    "TRAILER_NONE",
    "Beverage",
    "BrewAction",
    "MachineProfile",
    "PowerCommand",
    "ProfileSlot",
    "RecipeCatalogue",
    "SessionGate",
    "StatisticEntry",
    "StatisticsReport",
    "WritableSetting",
    "answer_flag",
    "answer_id",
    "blob_family",
    "brew_param_included",
    "build_bean_system",
    "build_brew",
    "build_catalog",
    "build_factory_descriptor",
    "build_monitor_request",
    "build_power",
    "build_priority_list",
    "build_profile_names",
    "build_profile_select",
    "build_read",
    "build_read_block",
    "build_read_param",
    "build_read_params",
    "build_recipe_names",
    "build_recipe_values",
    "build_statistics_page",
    "build_striker_handshake",
    "build_write_param",
    "catalog_beverage_ids",
    "counter_breakdown",
    "decode_a2_page",
    "decode_blob",
    "encode_for_transport",
    "fingerprint",
    "interpret",
    "is_sync_timeout",
    "parse_a9_ack",
    "parse_counter_value",
    "parse_profile_names",
    "parse_settings",
    "parse_simple_ack",
    "parse_tlv",
    "parse_triples",
    "parse_water_volume_liters",
    "parse_write_ack",
    "profile_from_map",
    "resolve_cloud_breakdowns",
    "resolve_cloud_counters",
    "trim_frame",
    "verify_frame",
]
